services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "43000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - dokkan-network
    volumes:
      - ./data:/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${API_HOST:-http://localhost}:43000
    ports:
      - "40080:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${API_HOST:-http://localhost}:43000
    depends_on:
      - backend
    networks:
      - dokkan-network
    restart: unless-stopped

networks:
  dokkan-network:
    driver: bridge 