services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "43000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - dokkan-network
    volumes:
      - ./data:/data
    container_name: dokkan-backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://dokkan.cid.wiki
    ports:
      - "40080:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://dokkan.cid.wiki
    depends_on:
      - backend
    networks:
      - dokkan-network
    restart: unless-stopped
    container_name: dokkan-frontend

networks:
  dokkan-network:
    name: dokkan-network
    driver: bridge 